"""realace min/max with ranges in mosnter

Revision ID: 3e32f9fec408
Revises: 90c90f5ac0bc
Create Date: 2021-08-25 18:37:37.906511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e32f9fec408'
down_revision = '90c90f5ac0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster', sa.Column('mp', postgresql.INT4RANGE(), nullable=True))
    op.add_column('monster', sa.Column('ap', postgresql.INT4RANGE(), nullable=True))
    op.add_column('monster', sa.Column('hp', postgresql.INT4RANGE(), nullable=True))
    op.add_column('monster', sa.Column('earthres', postgresql.INT4RANGE(), nullable=True))
    op.add_column('monster', sa.Column('waterres', postgresql.INT4RANGE(), nullable=True))
    op.add_column('monster', sa.Column('fireres', postgresql.INT4RANGE(), nullable=True))
    op.add_column('monster', sa.Column('airres', postgresql.INT4RANGE(), nullable=True))
    op.add_column('monster', sa.Column('neutralres', postgresql.INT4RANGE(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monster', 'neutralres')
    op.drop_column('monster', 'airres')
    op.drop_column('monster', 'fireres')
    op.drop_column('monster', 'waterres')
    op.drop_column('monster', 'earthres')
    op.drop_column('monster', 'hp')
    op.drop_column('monster', 'ap')
    op.drop_column('monster', 'mp')
    # ### end Alembic commands ###
