"""remove missed neutral_steal from weapons

Revision ID: 41c9a9eb1a50
Revises: 12a4779586cb
Create Date: 2021-08-26 12:33:56.075828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41c9a9eb1a50'
down_revision = '12a4779586cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapon', 'neutral_steal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weapon', sa.Column('neutral_steal', postgresql.INT4RANGE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
