"""Add crit_hit_bonus and conditions field to weaapn

Revision ID: 4c3f53f3a9c7
Revises: b0e7ad8fc281
Create Date: 2021-08-21 13:45:58.985905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3f53f3a9c7'
down_revision = 'b0e7ad8fc281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weapon', sa.Column('crit_hit_bonus', sa.Integer(), nullable=False))
    op.add_column('weapon', sa.Column('conditions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapon', 'conditions')
    op.drop_column('weapon', 'crit_hit_bonus')
    # ### end Alembic commands ###
