"""Added Vitality column to equipment Table

Revision ID: 5b08239ecb0e
Revises: 4a8656fa0788
Create Date: 2021-08-12 08:57:59.572421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b08239ecb0e'
down_revision = '4a8656fa0788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('min_vitality', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('max_vitality', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'max_vitality')
    op.drop_column('equipment', 'min_vitality')
    # ### end Alembic commands ###
