"""realace min/max with ranges in equipment

Revision ID: 6878867232a1
Revises: 3e32f9fec408
Create Date: 2021-08-25 18:56:44.652090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6878867232a1'
down_revision = '3e32f9fec408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('vitality', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('ap', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('ap_parry', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('ap_reduction', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('agility', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('air_damage', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('percent_air_res', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('chance', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('water_damage', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('percent_water_res', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('prospecting', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('intelligence', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('fire_damage', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('percent_fire_res', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('strength', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('earth_damage', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('percent_earth_res', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('pods', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('wisdom', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('neutral_damage', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('percent_neutral_res', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('damage', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('damage_reflected', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('critical_damage', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('critical_res', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('percent_critical', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('pushback_damage', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('pushback_res', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('dodge', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('heals', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('initiative', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('lock', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('mp', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('mp_parry', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('mp_reduction', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('percent_melee_damage', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('percent_melee_res', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('percent_ranged_damage', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('percent_ranged_res', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('percent_spell_damage', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('percent_weapon_damage', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('summons', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('trap_damage', postgresql.INT4RANGE(), nullable=True))
    op.add_column('equipment', sa.Column('range', postgresql.INT4RANGE(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'range')
    op.drop_column('equipment', 'trap_damage')
    op.drop_column('equipment', 'summons')
    op.drop_column('equipment', 'percent_weapon_damage')
    op.drop_column('equipment', 'percent_spell_damage')
    op.drop_column('equipment', 'percent_ranged_res')
    op.drop_column('equipment', 'percent_ranged_damage')
    op.drop_column('equipment', 'percent_melee_res')
    op.drop_column('equipment', 'percent_melee_damage')
    op.drop_column('equipment', 'mp_reduction')
    op.drop_column('equipment', 'mp_parry')
    op.drop_column('equipment', 'mp')
    op.drop_column('equipment', 'lock')
    op.drop_column('equipment', 'initiative')
    op.drop_column('equipment', 'heals')
    op.drop_column('equipment', 'dodge')
    op.drop_column('equipment', 'pushback_res')
    op.drop_column('equipment', 'pushback_damage')
    op.drop_column('equipment', 'percent_critical')
    op.drop_column('equipment', 'critical_res')
    op.drop_column('equipment', 'critical_damage')
    op.drop_column('equipment', 'damage_reflected')
    op.drop_column('equipment', 'damage')
    op.drop_column('equipment', 'percent_neutral_res')
    op.drop_column('equipment', 'neutral_damage')
    op.drop_column('equipment', 'wisdom')
    op.drop_column('equipment', 'pods')
    op.drop_column('equipment', 'percent_earth_res')
    op.drop_column('equipment', 'earth_damage')
    op.drop_column('equipment', 'strength')
    op.drop_column('equipment', 'percent_fire_res')
    op.drop_column('equipment', 'fire_damage')
    op.drop_column('equipment', 'intelligence')
    op.drop_column('equipment', 'prospecting')
    op.drop_column('equipment', 'percent_water_res')
    op.drop_column('equipment', 'water_damage')
    op.drop_column('equipment', 'chance')
    op.drop_column('equipment', 'percent_air_res')
    op.drop_column('equipment', 'air_damage')
    op.drop_column('equipment', 'agility')
    op.drop_column('equipment', 'ap_reduction')
    op.drop_column('equipment', 'ap_parry')
    op.drop_column('equipment', 'ap')
    op.drop_column('equipment', 'vitality')
    # ### end Alembic commands ###
