"""Crit_hit_bonus on weapon table can be null

Revision ID: 90c90f5ac0bc
Revises: 4c3f53f3a9c7
Create Date: 2021-08-21 13:59:43.698987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c90f5ac0bc'
down_revision = '4c3f53f3a9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weapon', 'crit_hit_bonus',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weapon', 'crit_hit_bonus',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
