"""Add Monster Table

Revision ID: a51d5e6498be
Revises: 
Create Date: 2021-07-18 15:43:29.360605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51d5e6498be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monster',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('minlevel', sa.Integer(), nullable=False),
    sa.Column('maxlevel', sa.Integer(), nullable=False),
    sa.Column('minmp', sa.Integer(), nullable=False),
    sa.Column('maxmp', sa.Integer(), nullable=False),
    sa.Column('minap', sa.Integer(), nullable=False),
    sa.Column('maxap', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=128), nullable=False),
    sa.Column('minhp', sa.Integer(), nullable=False),
    sa.Column('maxhp', sa.Integer(), nullable=False),
    sa.Column('minearthres', sa.Integer(), nullable=False),
    sa.Column('maxearthres', sa.Integer(), nullable=False),
    sa.Column('minwaterres', sa.Integer(), nullable=False),
    sa.Column('maxwaterres', sa.Integer(), nullable=False),
    sa.Column('minfireres', sa.Integer(), nullable=False),
    sa.Column('maxfireres', sa.Integer(), nullable=False),
    sa.Column('minairres', sa.Integer(), nullable=False),
    sa.Column('maxairres', sa.Integer(), nullable=False),
    sa.Column('minneutralres', sa.Integer(), nullable=False),
    sa.Column('maxneutralres', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monster')
    # ### end Alembic commands ###
