"""Add user_per_turn column to weapon. Add relationship between weapon and ingredients table

Revision ID: b0e7ad8fc281
Revises: 97fae0e5221f
Create Date: 2021-08-21 10:07:13.923560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e7ad8fc281'
down_revision = '97fae0e5221f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('weapon_id', sa.Integer(), nullable=True))
    op.drop_index('fki_ingredient_equipment_id_fkey', table_name='ingredient')
    op.create_foreign_key(None, 'ingredient', 'weapon', ['weapon_id'], ['id'])
    op.add_column('weapon', sa.Column('use_per_turn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapon', 'use_per_turn')
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.create_index('fki_ingredient_equipment_id_fkey', 'ingredient', ['equipment_id'], unique=False)
    op.drop_column('ingredient', 'weapon_id')
    # ### end Alembic commands ###
