from models.base import Base
from sqlalchemy import Column
from sqlalchemy.orm import relationship
from sqlalchemy.types import String, Integer

class Equipment(Base):
    __tablename__ = 'equipment'
    id = Column(Integer, primary_key=True, nullable=False, autoincrement=False)
    type = Column(String, nullable = False)
    level = Column(Integer, nullable = False)
    name = Column(String, nullable = False)
    description = Column(String, nullable = True)
    ap = Column(Integer, nullable = True)
    ap_parry = Column(Integer, nullable = True)
    ap_reduction = Column(Integer, nullable = True)
    agility = Column(Integer, nullable = True)
    air_damage = Column(Integer, nullable = True)
    percent_air_res = Column(Integer, nullable = True)
    chance = Column(Integer, nullable = True)
    water_damage = Column(Integer, nullable = True)
    percent_water_res = Column(Integer, nullable = True)
    prospecting = Column(Integer, nullable = True)
    intelligence = Column(Integer, nullable = True)
    fire_damage = Column(Integer, nullable = True)
    percent_fire_res = Column(Integer, nullable = True)
    strength = Column(Integer, nullable = True)
    earth_damage = Column(Integer, nullable = True)
    percent_earth_res = Column(Integer, nullable = True)
    pods = Column(Integer, nullable = True)
    wisdom = Column(Integer, nullable = True)
    neutral_damage = Column(Integer, nullable = True)
    percent_neutral_res = Column(Integer, nullable = True)
    damage = Column(Integer, nullable = True)
    damage_reflected = Column(Integer, nullable = True)
    critical_damage = Column(Integer, nullable = True)
    critical_res = Column(Integer, nullable = True)
    percent_critical = Column(Integer, nullable = True)
    pushback_damage = Column(Integer, nullable = True)
    pushback_res = Column(Integer, nullable = True)
    dodge = Column(Integer, nullable = True)
    heals = Column(Integer, nullable = True)
    initiative = Column(Integer, nullable = True)
    lock = Column(Integer, nullable = True)
    mp = Column(Integer, nullable = True)
    mp_parry = Column(Integer, nullable = True)
    mp_reduction = Column(Integer, nullable = True)
    percent_melee_damage = Column(Integer, nullable = True)
    percent_melee_res = Column(Integer, nullable = True)
    percent_ranged_damage = Column(Integer, nullable = True)
    percent_ranged_res = Column(Integer, nullable = True)
    percent_spell_damage = Column(Integer, nullable = True)
    percent_weapon_damage = Column(Integer, nullable = True)
    summons = Column(Integer, nullable = True)
    trap_damage = Column(Integer, nullable = True)
    range = Column(Integer, nullablej = True)
    recipe = relationship('Recipe', back_populates='equipment', uselist=False, nullable= False)