from models.base import Base
from sqlalchemy import Column
from sqlalchemy.orm import relationship
from sqlalchemy.types import String, Integer

#Equiment model class - gathers identification, effects, and associates to crafting recipe
class Equipment(Base):
    __tablename__ = 'equipment'
    #identification
    id = Column(Integer, primary_key=True, nullable=False, autoincrement=False)
    type = Column(String, nullable = False)
    level = Column(Integer, nullable = False)
    name = Column(String, nullable = False)
    description = Column(String, nullable = True)
    #Core Effects
    min_ap = Column(Integer, nullable = True)
    max_ap = Column(Integer, nullable = True)
    min_ap_parry = Column(Integer, nullable = True)
    max_ap_parry = Column(Integer, nullable = True)
    min_ap_reduction = Column(Integer, nullable = True)
    max_ap_reduction = Column(Integer, nullable = True)
    min_agility = Column(Integer, nullable = True)
    max_agility = Column(Integer, nullable = True)
    min_air_damage = Column(Integer, nullable = True)
    max_air_damage = Column(Integer, nullable = True)
    min_percent_air_res = Column(Integer, nullable = True)
    max_percent_air_res = Column(Integer, nullable = True)
    min_chance = Column(Integer, nullable = True)
    max_chance = Column(Integer, nullable = True)
    min_water_damage = Column(Integer, nullable = True)
    max_water_damage = Column(Integer, nullable = True)
    min_percent_water_res = Column(Integer, nullable = True)
    max_percent_water_res = Column(Integer, nullable = True)
    min_prospecting = Column(Integer, nullable = True)
    max_prospecting = Column(Integer, nullable = True)
    min_intelligence = Column(Integer, nullable = True)
    max_intelligence = Column(Integer, nullable = True)
    min_fire_damage = Column(Integer, nullable = True)
    max_fire_damage = Column(Integer, nullable = True)
    min_percent_fire_res = Column(Integer, nullable = True)
    max_percent_fire_res = Column(Integer, nullable = True)
    min_strength = Column(Integer, nullable = True)
    max_strength = Column(Integer, nullable = True)
    min_earth_damage = Column(Integer, nullable = True)
    max_earth_damage = Column(Integer, nullable = True)
    min_percent_earth_res = Column(Integer, nullable = True)
    max_percent_earth_res = Column(Integer, nullable = True)
    min_pods = Column(Integer, nullable = True)
    max_pods = Column(Integer, nullable = True)
    min_wisdom = Column(Integer, nullable = True)
    max_wisdom = Column(Integer, nullable = True)
    min_neutral_damage = Column(Integer, nullable = True)
    max_neutral_damage = Column(Integer, nullable = True)
    min_percent_neutral_res = Column(Integer, nullable = True)
    max_percent_neutral_res = Column(Integer, nullable = True)
    min_damage = Column(Integer, nullable = True)
    max_damage = Column(Integer, nullable = True)
    min_damage_reflected = Column(Integer, nullable = True)
    max_damage_reflected = Column(Integer, nullable = True)
    min_critical_damage = Column(Integer, nullable = True)
    max_critical_damage = Column(Integer, nullable = True)
    min_critical_res = Column(Integer, nullable = True)
    max_critical_res = Column(Integer, nullable = True)
    min_percent_critical = Column(Integer, nullable = True)
    max_percent_critical = Column(Integer, nullable = True)
    min_pushback_damage = Column(Integer, nullable = True)
    max_pushback_damage = Column(Integer, nullable = True)
    min_pushback_res = Column(Integer, nullable = True)
    max_pushback_res = Column(Integer, nullable = True)
    min_dodge = Column(Integer, nullable = True)
    max_dodge = Column(Integer, nullable = True)
    min_heals = Column(Integer, nullable = True)
    max_heals = Column(Integer, nullable = True)
    min_initiative = Column(Integer, nullable = True)
    max_initiative = Column(Integer, nullable = True)
    min_lock = Column(Integer, nullable = True)
    max_lock = Column(Integer, nullable = True)
    min_mp = Column(Integer, nullable = True)
    max_mp = Column(Integer, nullable = True)
    min_mp_parry = Column(Integer, nullable = True)
    max_mp_parry = Column(Integer, nullable = True)
    min_mp_reduction = Column(Integer, nullable = True)
    max_mp_reduction = Column(Integer, nullable = True)
    min_percent_melee_damage = Column(Integer, nullable = True)
    max_percent_melee_damage = Column(Integer, nullable = True)
    min_percent_melee_res = Column(Integer, nullable = True)
    max_percent_melee_res = Column(Integer, nullable = True)
    min_percent_ranged_damage = Column(Integer, nullable = True)
    max_percent_ranged_damage = Column(Integer, nullable = True)
    min_percent_ranged_res = Column(Integer, nullable = True)
    max_percent_ranged_res = Column(Integer, nullable = True)
    min_percent_spell_damage = Column(Integer, nullable = True)
    max_percent_spell_damage = Column(Integer, nullable = True)
    min_percent_weapon_damage = Column(Integer, nullable = True)
    max_percent_weapon_damage = Column(Integer, nullable = True)
    min_summons = Column(Integer, nullable = True)
    max_summons = Column(Integer, nullable = True)
    min_trap_damage = Column(Integer, nullable = True)
    max_trap_damage = Column(Integer, nullable = True)
    min_range = Column(Integer, nullable = True)
    max_range = Column(Integer, nullable = True)
    #relationships
    recipe = relationship('Recipe', back_populates='equipment', uselist=False)